name: CI / Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ ${{
            secrets.DEPLOY_USER
          }}@${{ secrets.DEPLOY_HOST }}:/root/clan-agent/

    - name: Restart PM2 on server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /root/clan-agent
          pm2 restart clan-agent --update-env
        EOF
